### ISSUE TITLE
Unable to Access Cubic Function in SimpleCrystals.jl

### ISSUE THREAD

**Issue by Matheus-gif** [ejmeitz/SimpleCrystals.jl#2]
I was following the user defined crystal structures tutorial, and it looks like I'm unable to create the NaCl crystal structure. I'm working in VSCode using a notebook extension. Here's my attempt:

```julia
using SimpleCrystals
#import SimpleCrystals.CrystalStructures

function NaCl1(a, N::SVector{3})
    lattice = BravaisLattice(Cubic(a), Primitive())
    basis = [Atom(:Na, SVector(zero(a), zero(a), zero(a)), charge = 1.0u"q"),
             Atom(:Na, SVector(0.5*a,zero(a),0.5*a), charge = 1.0u"q"),
             Atom(:Na, SVector(zero(a), 0.5*a, 0.5*a), charge = 1.0u"q"),
             Atom(:Na, SVector(0.5*a,0.5*a,zero(a)), charge = 1.0u"q"),
             Atom(:Cl, SVector(0.5*a, zero(a), zero(a)), charge = -1.0u"q"),
             Atom(:Cl, SVector(zero(a), 0.5*a, zero(a)), charge = -1.0u"q"),
             Atom(:Cl, SVector(zero(a),zero(a),0.5*a), charge = -1.0u"q"),
             Atom(:Cl, SVector(0.5*a, 0.5*a, 0.5*a), charge = -1.0u"q")]
    return Crystal(lattice,basis,N)
end

NaCl1(0.54u"nm", SVector(3, 3, 3))
```

Here's the error:
UndefVarError: `Cubic` not defined

Stacktrace:
 [1] NaCl1(a::Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, N::SVector{3, Int64})
   @ Main c:\Users\User\Desktop\tratar_dados\tutorial_julia\Tutorial crystal\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_W0sZmlsZQ==.jl:5
 [2] top-level scope
   @ c:\Users\User\Desktop\tratar_dados\tutorial_julia\Tutorial crystal\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_W0sZmlsZQ==.jl:1
   
 
Environment Details:

Julia Version: 1.9.2
SimpleCrystals.jl Version: v0.2.0
OS: Windows 11

**Comment by ejmeitz** [comment]
Oh, I think I just forgot to update the example, it should be `CubicLattice` instead of `Cubic`. Let me know if that still doesn't work!

Edit: I guess I updated on GitHub but not the version pushed to the Julia registry maybe. How were you accessing the documentation/readme?

**Comment by Matheus-gif** [comment]
Thank you very much, it worked perfectly.

Hmm, I see. I was using the following link
https://docs.juliahub.com/General/SimpleCrystals/stable/

Indeed it's different from the other link
https://github.com/ejmeitz/SimpleCrystals.jl

I did a pretty naive research, I just googled "how to draw crystal lattices in Julia" , which lead me to the first link

**Comment by Matheus-gif** [comment]
If it's okay, I have one more question, but I'm not sure if I should either open a new issue or continue with this one. How do you manage to plot the unit cells on your GitHub? I'm working on my master thesis and I'm trying to display these cells also

**Comment by ejmeitz** [comment]
Ah, ok. I just updated the docs, hopefully they match the ReadMe once those changes go live.

I rendered the images in the ReadMe inside of [OVITO](https://www.ovito.org/). The free version should let you use the OpenGL renderer. I was working on integrating this into a Julia package but for now you'll have to save the SimpleCrystals structure as an xyz file and then move it into OVITO and render the image.

If you run into other large bugs or issues with the output please create a separate issue. I tested the functionality pretty thoroughly, but in my research I ultimately only use a small subset of the functions.

**Comment by Matheus-gif** [comment]
Got it. 

Understood, I will. Thank you once again for this great package.
