### ISSUE TITLE
AtomsBase compat

### ISSUE THREAD

**Issue by jgreener64** [ejmeitz/SimpleCrystals.jl#3]
With the release of AtomsBase v0.4 it would be good to make this package compatible.

**Comment by ejmeitz** [comment]
@jgreener All done, will require some small API changes in Molly to the constructor that creates a Molly system from a Crystal. Use v0.3.1. I'll make a PR on Molly in the near future.

There's also some other API changes to be made in Molly from other AtomsBase changes.

**Comment by jgreener64** [comment]
Great, thanks.

**Comment by jgreener64** [comment]
Did you get round to making the Molly changes? If not I can do it in the next couple of days.

**Comment by ejmeitz** [comment]
Unfortunately not.
